config/routes.rb
Rails.application.routes.draw do


  namespace :api do

    resources :authors
    resources :users
    resources :books do
    resources :reviews
    resources :rates, only: :create
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :description, presence: true

  has_many :books, dependent: :destroy
  has_many :reviews, through: :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews
  has_many: rates

  validates :title, :description, presence: true
end

app/models/rates.rb
class Rate < ApplicationRecord
    belongs_to :book
  end

app/models/review.rb
class Review < ApplicationRecord
    validates :rating, :comment, presence: true
    belongs_to :book 
    belongs_to :user
    has_one :rating
    has_one :comment
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  has_many :books
  has_many :reviews
end

app/controllers/api/authors_controller.rb
module API
  class AuthorsController < ApplicationController
    def create
      author = Author.new(allowed_params)

      if author.save
        render json: author
      else
        render json: { errors: author.errors.full_messages }
      end
    end

    def index
      render json: Author.all
    end

    def show
      render json: Author.find(params[:id])
    end

    def update
      author = Author.find(params[:id])

      if author.update(allowed_params)
        render json: author
      else
        render json: { errors: author.errors.full_messages }
      end
    end

    private

    def allowed_params
      params.permit(
        :description,
        :first_name,
        :last_name,
        :website,
        genres: []
      )
    end
  end
end

app/controllers/api/books_controller.rb
module API
  class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    def index
      render json: Book.all
    end

    def new
      book = Book.new
    end
    
    def create
      book = Book.new(allowed_params)

      if book.save
        render json: book
      else
        render json: { errors: book.errors.full_messages }
      end
    end

    def show
    end

    def edit
    end

    def destroy
      @book.destroy
      redirect_to root_path
    end

    def update
      book = Book.find(params[:id])

      if book.update(allowed_params)
        render json: book
      else

        render json: { errors: book.errors.full_messages }
      end
    end

    private

    def allowed_params
      params.permit(
        :author_id,
        :description,
        :publish_date,
        :rating,
        :title
      )
    end

    def find_book
      render json: Book.find(params[:id])
  end
end

end

app/controllers/api/users_controller.rb
module API
  class UsersController < ApplicationController
    def create
      user = User.new(allowed_params)

      if user.save
        render json: user
      else
        render json: { errors: user.errors.full_messages }
      end
    end

    def index
      render json: User.all
    end

    def show
      render json: User.find(params[:id])
    end

    def update
      user = User.find(params[:id])

      if user.update(allowed_params)
        render json: user
      else
        render json: { errors: user.errors.full_messages }
      end
    end

    private

    def allowed_params
      params.permit(
        :first_name,
        :last_name
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  protect_from_forgery with: :exception
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
    before_filter :require_login

    def create
      @rate = Rate.create! rate_params

      render json: { average: rating.average }
    end

    private

    def rateable
      @rate.rateable
    end

    def rating
      rateable.rating(@rate.dimension)
    end

    def rate_params
      params.require(:rate).permit!.merge(rater_id: current_rater.id)
    end

    def require_login
      raise SeemsRateable::Errors::NoCurrentRaterError unless current_rater
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
    render json: @reviews
  end

    def index
      @reviews = Review.all
     render json: @reviews
    end

    def create
        @review = Review.new(allowed_params)
  
        if @review.save
          render json: @review
        else
          render json: { errors: review.errors.full_messages }
        end
      end

        def show
            render json: Review.find(params[:id])
        end
 
        def update
            @review = Review.find(params[:id])
      
            if review.update(allowed_params)
              render json: @review
            else
              render json: { errors: review.errors.full_messages }
            end
          end

        def destroy
            @review.destroy
        end


        private

        def allowed_params
            params.permit(
              :comment,
              :rating
            )
          end
        end
      end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "Book Review", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
            
            <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>	

            
</body>
</html>

app/views/layouts/books/_form.html.erb
<%= simple_form_for @book do |f| %>
<%= f.input :title, label: "Book Title" %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.button :submit %>
<% end %>

app/views/layouts/books/index.html.erb
<% @books.each do |book| %>
<h2><%= link_to book.title, book_path(book) %></h2>
<% end %>

<%= link_to "Add Book", %>

app/views/layouts/books/new.html.erb
<h1>New Book</h1>

<%= render 'form %>

app/views/layouts/books/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
  </div>

  <div class="col-md-8">
    <div class="book-info">
      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"><span>From </span><%= @book.author %></h3>
      <h2 class="avg-rating">Average Rating</h2>
      <div class="average-review-rating" data-score="<%= @average_review %>"></div>
      <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
      <p class="book-desc"><%= @book.description %></p>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-md-4">

    <div class="reviews">
      <!-- where reviews will go -->
      <h1>Reviews</h1>
      <%= render @book.reviews %>

      <div>
        <%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
      </div>

    </div>
  </div>
</div>

<div class="links btn-group">

  <%= link_to "Back", root_path, class: "btn btn-custom" %>
  <% if user_signed_in? %>
    <% if @book.user_id == current_user.id %>
      <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
      <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" },
       class: "btn btn-custom" %>
    <% end %>
  <% end %>

app/views/layouts/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/layouts/reviews/_review.html.erb
<div class="review">

  <div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.rating %></p>
  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
      <%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
      <%= link_to "Delete", book_review_path(review.book, review), method: :delete,
      data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/layouts/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="edit-review-form">

    <h1>Edit Review</h1>

    <%= simple_form_for([@book, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, :class => 'btn-custom2' %>
    <% end %>

  </div>

</div>

app/views/layouts/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-review-form">

    <h1>New Review</h1>

    <%= render 'form' %>

  </div>

</div>